"use client"

import * as React from "react"
import { 
  CheckCircle2Icon, 
  DownloadIcon, 
  PrinterIcon, 
  Share2Icon,
  ShieldCheckIcon,
  QrCodeIcon
} from "lucide-react"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { QRCodeSVG } from "qrcode.react"

interface ReceiptData {
  productName: string
  quantity: number
  price: number
  ebmNumber: string
  timestamp: string
  customerTIN?: string
}

export function RRAReceiptDialog({ 
  open, 
  onOpenChange,
  data 
}: { 
  open: boolean
  onOpenChange: (open: boolean) => void
  data: ReceiptData | null
}) {
  if (!data) return null

  const total = data.quantity * data.price
  const vat = total * 0.18 // 18% VAT in Rwanda

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[400px] p-0 overflow-hidden bg-white text-black">
        <div className="bg-primary/10 p-6 flex flex-col items-center text-center gap-2 border-b">
          <div className="size-12 rounded-full bg-primary flex items-center justify-center shadow-lg mb-2">
            <ShieldCheckIcon className="size-6 text-black" />
          </div>
          <DialogTitle className="text-xl font-bold">RRA Certified Receipt</DialogTitle>
          <p className="text-xs font-medium text-primary/80 uppercase tracking-widest">EBM V2 VALIDATED</p>
        </div>

        <div className="p-8 space-y-6 font-mono text-[13px]">
          {/* Header */}
          <div className="text-center space-y-1">
            <h3 className="font-bold text-base uppercase">STOCKR LTD</h3>
            <p>KIGALI, RWANDA</p>
            <p>TIN: 123456789</p>
            <p>Tel: +250 788 000 000</p>
          </div>

          <div className="border-t border-dashed pt-4 space-y-1">
            <div className="flex justify-between">
              <span>Date:</span>
              <span>{new Date(data.timestamp).toLocaleString()}</span>
            </div>
            <div className="flex justify-between font-bold">
              <span>Receipt #:</span>
              <span>{data.ebmNumber}</span>
            </div>
          </div>

          {/* Items */}
          <div className="border-t border-dashed pt-4 space-y-2">
            <div className="flex justify-between font-bold pb-1 border-b border-muted">
              <span>Item</span>
              <span>Total</span>
            </div>
            <div className="flex justify-between items-start">
              <div className="max-w-[200px]">
                <p className="font-bold">{data.productName}</p>
                <p className="text-xs text-muted-foreground">{data.quantity} x {data.price.toLocaleString()} RWF</p>
              </div>
              <span className="font-bold">{total.toLocaleString()}</span>
            </div>
          </div>

          {/* Totals */}
          <div className="border-t border-dashed pt-4 space-y-1">
            <div className="flex justify-between">
              <span>Net Amount:</span>
              <span>{(total - vat).toLocaleString()} RWF</span>
            </div>
            <div className="flex justify-between">
              <span>VAT (18%):</span>
              <span>{vat.toLocaleString()} RWF</span>
            </div>
            <div className="flex justify-between text-lg font-bold pt-2">
              <span>TOTAL:</span>
              <span>{total.toLocaleString()} RWF</span>
            </div>
          </div>

          {/* QR & Verification */}
          <div className="flex flex-col items-center gap-4 pt-6">
            <div className="p-2 bg-white border-2 border-black/5 rounded-lg shadow-sm">
              <QRCodeSVG 
                value={`https://rra.gov.rw/verify/${data.ebmNumber}`} 
                size={100}
                level="M"
              />
            </div>
            <p className="text-[10px] text-center text-muted-foreground max-w-[250px]">
              Scan to verify this transaction on the RRA portal. 
              Electronic Receipt generated by Stockr VSDC.
            </p>
          </div>
        </div>

        <div className="bg-muted/30 p-4 border-t flex gap-2">
          <Button variant="outline" size="sm" className="flex-1 gap-2">
            <PrinterIcon className="size-4" />
            Print
          </Button>
          <Button variant="outline" size="sm" className="flex-1 gap-2">
            <DownloadIcon className="size-4" />
            PDF
          </Button>
          <Button className="flex-1 gap-2 bg-primary text-black hover:bg-primary/90 font-bold">
            <Share2Icon className="size-4" />
            Share
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
